### ISSUE TITLE
Adoção/Criação do "Framework" CSS?

### ISSUE THREAD

**Issue by lai32290** [Minhacps/votasp-app#10]
Vocês acham que a vale a pena da gente criar o CSS do zero ou usamos algum desses bootstrap da vida? Qual recomendam?

Se eu não me engano, da outra vez usamos [Material Design](https://material.io/design/) (é só uma informação, não é uma recomendação)

**Comment by lai32290** [comment]
tem o [Semantic UI](https://react.semantic-ui.com/introduction) que é legal também, e já tem a versão integrado com React.

**Comment by victorperin** [comment]
Não conhecia esse Semantic UI. Parece interessante.
@notnotgabriel e @victormiguez o que vocês acham?
