### ISSUE TITLE
Fotos dos candidatos estão distorcidas

### ISSUE THREAD

**Issue by bwowk** [Minhacps/votasp-app#122]
As fotos dos candidatos, por não serem quadradas, estão aparecendo comprimidas verticalmente ao serem ajustadas para o formato circular:
![image](https://user-images.githubusercontent.com/847070/44949172-b1be3380-ae02-11e8-9d21-a2af791cee1a.png)

**Comment by victormiguez** [comment]
Corrigido no PR #130.
