### ISSUE TITLE
Sugestões de melhoria app

### ISSUE THREAD

**Issue by VanessaAzuos18** [Minhacps/votasp-app#43]
1. Tirar o border (branco) no top e bottom ou colocar nos lados na tela de login/cadastro.
2. Aumentar um pouco a fonte dos botões entrar e cadastrar ou então deixar com a estilização bold na tela de login/cadastro.
3. Inserir o campo "confirmar senha" na tela de cadastro
4. Inserir alguma opção (pode ser configurações ou algo similar) para alterar senha quando o usuário estiver logado.
5. Inserir a opção recuperar senha na tela de login.

**Comment by victorperin** [comment]
@VanessaAzuos18 você pode quebrar em 5 issues diferentes, por favor?
Acredito que simplifica pro pessoal se organizar.
