### ISSUE TITLE
Botões ficam desconfigurados. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votasp-app#79]
Os botões pular e afinidade perdem a configuração nas questões  provavelmente devido ao tamanho as mesmas 21, 29, 32, 35, 36 e 40.

**Comment by notnotgabriel** [comment]
@wab030 não consegui identificar o problema testando aqui. Tem um print da tela pra gente ver como fica?

**Comment by wab030** [comment]
Desencana Gabriel, tentei simular aqui mas não consegui. Se eu conseguir algo tiro um print e reabro o issue.
